name: mimojo-consumer-identity-service-qnb

on:
  push:
  workflow_dispatch: {}

jobs:
  transform-local-files:
    name: Transform Files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Upload Transformed Files
        uses: actions/upload-artifact@v4
        with:
          name: transformed-files
          path: |
            README.md


  build-and-deploy:
    needs: transform-local-files
    uses: mojosoln/gh-shared-templates/.github/workflows/build-and-deploy-template-hw.yml@main
    with:
      deployment_name: "mimojo-consumer-identity-service-qnb"
      image_name: "mimojo-consumer-identity-service-qnb"
      env_secrets: "consumer-identity-service-qnb-env-file"
      dockerfile: "Dockerfile"
      profile: javascript

    secrets:
      ACR_TOKEN: ${{ secrets.ACR_TOKEN }}
      ACR_TOKEN_PROD: ${{ secrets.ACR_TOKEN_PROD }}
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      HW_ACCESS_KEY: ${{ secrets.HW_ACCESS_KEY }}
      HW_SECRET_KEY: ${{ secrets.HW_SECRET_KEY }}
      SWR_USERNAME: ${{ secrets.SWR_USERNAME }}
      SWR_PASSWORD: ${{ secrets.SWR_PASSWORD }}
      HW_DEV_DB_PASSWORD: ${{ secrets.HW_DEV_DB_PASSWORD }}
      HW_STAGE_DB_PASSWORD: ${{ secrets.HW_STAGE_DB_PASSWORD }}
      HW_PROD_DB_PASSWORD: ${{ secrets.HW_PROD_DB_PASSWORD }}
      HW_DEV_CCE_CLUSTER_KUBECONFIG: ${{ secrets.HW_DEV_CCE_CLUSTER_KUBECONFIG }}
      HW_STAGE_CCE_CLUSTER_KUBECONFIG: ${{ secrets.HW_STAGE_CCE_CLUSTER_KUBECONFIG }}
      HW_PRELIVE_CCE_CLUSTER_KUBECONFIG: ${{ secrets.HW_PRELIVE_CCE_CLUSTER_KUBECONFIG }}
      HW_PROD_CCE_CLUSTER_KUBECONFIG: ${{ secrets.HW_PROD_CCE_CLUSTER_KUBECONFIG }}
